Name: Build and deploy site to GitHub-Pages

on:
  push:
    branches:
     - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: helaili/jekyll-action@v2
        with
          token: ${{ secrets.XRS444_NET }}

