name: Build and deploy site to GitHub-Pages

on:
  push:
    branches:
     - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: actions/cache@master
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashfiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os  }-gems-
            
      - uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.XRS444_NET }}
          target_branch: 'gh-pages'
